### PR TITLE
A few new things added

### PR DESCRIPTION
**Pull request by farooqkz**
`:next` and `:!command` was added from my `.viminfo` file, the second is more useful for UN*X users.
Also changed `:tabe` to `:tabe [file]`.

### CODE REVIEW

**Comment by farooqkz** [comment]
@theicfire hello?

**Comment by chaselambda** [comment]
Hi @farooqkz thanks for checking in! If you resolve the conflicts this looks good to me, I appreciate it!

**Comment by farooqkz** [comment]
Done.
It's the first time I resolve a conflict, let's hope I've done it right.

**Comment by chaselambda** [comment]
Hmm it looks like there are issues. If you now look at the diff (the "files changed" tab), it says you have added many parts I don't think you meant to. Now there are duplicate pieces of the file.

This looks like a really tricky merge to make because of how much I've changed. My recommendation is that you just manually redo the changes -- I think that will be the fastest solution.

**Comment by farooqkz** [comment]
redo == closing this PR and opening another one?
seems like a good idea since my changes are trivial.

**Pull request closed without merging**
